develop:build:
  stage: build
  image:
    name: node
  only:
    refs:
      - develop
  script:
    - npm install react
    - npm run build
  artifacts:
    paths:
      - ./build
    expire_in: 1 hour

develop:deploy:
  stage: deploy
  image:
    name: node
  dependencies:
    - develop:build
  only:
    refs:
      - develop
  script:
    - npm install -g firebase-tools
    - firebase use lucacesarano-com --token "$FIREBASE_TOKEN"
    - firebase deploy -m "Pipe $CI_PIPELINE_ID Build $CI_BUILD_ID" --only hosting:beta-lucacesarano-com --non-interactive --token "$FIREBASE_TOKEN"
