prod:build:
  stage: build
  image:
    name: node
  only:
    refs:
      - master
  variables:
    WORKSPACE: prod
  script:
    - npm install react
    - npm run build
  artifacts:
    paths:
      - /build
    expire_in: 1 hour

prod:deploy:
  stage: deploy
  image:
    name: node
  dependencies:
    - prod:build
  only:
    refs:
      - master
  variables:
    WORKSPACE: prod
  script:
    - npm install -g firebase-tools
    - firebase use lucacesarano-com --token "$FIREBASE_TOKEN"
    - firebase deploy -m "Pipe $CI_PIPELINE_ID Build $CI_BUILD_ID" --only hosting:lucacesarano-com --non-interactive --token "$FIREBASE_TOKEN"
