prod:build:
  stage: build
  image:
    name: node
  only:
    refs:
      - master
  variables:
    WORKSPACE: prod
  script:
    - echo "hello world" >> artifact_file
    #- npm install react
    #- npm run build
  artifacts:
    paths:
      - .artifact_file
      - ./build
      - ./public
    expire_in: 1 day

prod:deploy:
  stage: deploy
  image:
    name: node
  dependencies:
    - prod:build
  only:
    refs:
      - master
  variables:
    WORKSPACE: prod
  script:
    - ls -a
    #- npm install -g firebase-tools
    #- firebase use lucacesarano-com --token "$FIREBASE_TOKEN"
    #- firebase deploy -m "Pipe $CI_PIPELINE_ID Build $CI_BUILD_ID" --only hosting:lucacesarano-com --non-interactive --token "$FIREBASE_TOKEN"
