prod:build:
  stage: build
  image:
    name: node
  only:
    refs:
      - master
  variables:
    WORKSPACE: prod
  script:
    - npm install react
    - npm run build

prod:deploy:
  stage: deploy
  image:
    name: hub.docker.com/r/andreysenov/firebase-tools
  only:
    refs:
      - master
  variables:
    WORKSPACE: prod
  script:
    - npm install -g firebase-tools
    - firebase use lucacesarano-com --token "$FIREBASE_TOKEN"
    - firebase deploy -m "Pipe $CI_PIPELINE_ID Build $CI_BUILD_ID" --only hosting:lucacesarano-com --non-interactive --token "$FIREBASE_TOKEN"