develop:build:
  stage: build
  image:
    name: node:16.13.1
  only:
    refs:
      - develop
  script:
    - npm install react
    - npm run build
  artifacts:
    paths:
      - ./build
    expire_in: 1 hour

develop:deploy:
  stage: deploy
  image:
    name: node:16.13.1
  dependencies:
    - develop:build
  only:
    refs:
      - develop
  before_script:
    - echo $FIARD_PRIVATE_KEY > "/private-key.json"
    - export GOOGLE_APPLICATION_CREDENTIALS="/private-key.json"
  script:
    - npm install -g firebase-tools
    - firebase use "lucacesarano-com"
    - firebase deploy -m "Pipe $CI_PIPELINE_ID Build $CI_BUILD_ID" --only hosting:beta-lucacesarano-com --non-interactive
