develop:build:
  stage: build
  image:
    name: node:20
  only:
    refs:
      - develop
  script:
    - npm ci
    - npm run build
  artifacts:
    paths:
      - ./dist
    expire_in: 1 hour

develop:deploy:
  stage: deploy
  image:
    name: andreysenov/firebase-tools
  dependencies:
    - develop:build
  only:
    refs:
      - develop
  before_script:
    - echo $FIARD_PRIVATE_KEY > "$HOME/private-key.json"
    - export GOOGLE_APPLICATION_CREDENTIALS="$HOME/private-key.json"
  script:
    - firebase use "lucacesarano-com"
    - firebase deploy -m "Pipe $CI_PIPELINE_ID Build $CI_BUILD_ID" --only hosting:beta-lucacesarano-com --non-interactive
