prod:build:
  stage: build
  image:
    name: node:16.13.1
  only:
    refs:
      - master
  script:
    - npm install react
    - npm run build
  artifacts:
    paths:
      - ./build
    expire_in: 1 hour

prod:deploy:
  stage: deploy
  image:
    name: andreysenov/firebase-tools
  dependencies:
    - prod:build
  only:
    refs:
      - master
  before_script:
    - echo $FIARD_PRIVATE_KEY > "/private-key.json"
    - export GOOGLE_APPLICATION_CREDENTIALS="/private-key.json"
  script:
    - firebase use "lucacesarano-com"
    - firebase deploy -m "Pipe $CI_PIPELINE_ID Build $CI_BUILD_ID" --only hosting:lucacesarano-com --non-interactive
