prod:unit:
  stage: build
  image:
    name: node:20
  interruptible: true
  variables:
    NPM_CONFIG_CACHE: "$CI_PROJECT_DIR/.npm"
    PLAYWRIGHT_BROWSERS_PATH: "$CI_PROJECT_DIR/.cache/ms-playwright"
  cache:
    key:
      files:
        - package-lock.json
    policy: pull-push
    paths:
      - .npm/
      - .cache/ms-playwright/
  rules:
    - if: $CI_COMMIT_BRANCH == "master"
    - when: never
  script:
    - npm ci --omit=peer
    - npm test

prod:e2e:
  stage: build
  image:
    name: node:20
  interruptible: true
  variables:
    NPM_CONFIG_CACHE: "$CI_PROJECT_DIR/.npm"
    PLAYWRIGHT_BROWSERS_PATH: "$CI_PROJECT_DIR/.cache/ms-playwright"
  cache:
    key:
      files:
        - package-lock.json
    policy: pull-push
    paths:
      - .npm/
      - .cache/ms-playwright/
  rules:
    - if: $CI_COMMIT_BRANCH == "master"
    - when: never
  script:
    - npm ci --omit=peer
    - npx playwright install chromium
    - npm run test:e2e -- --project=chromium
  artifacts:
    when: always
    paths:
      - ./playwright-report
      - ./test-results
    expire_in: 1 hour

prod:build:
  stage: build
  image:
    name: node:20
  interruptible: true
  variables:
    NPM_CONFIG_CACHE: "$CI_PROJECT_DIR/.npm"
  cache:
    key:
      files:
        - package-lock.json
    policy: pull-push
    paths:
      - .npm/
  rules:
    - if: $CI_COMMIT_BRANCH == "master"
    - when: never
  needs:
    - prod:unit
    - prod:e2e
  script:
    - npm ci --omit=peer
    - npm run build
  artifacts:
    paths:
      - ./dist
    expire_in: 1 hour

prod:deploy:
  stage: deploy
  image:
    name: andreysenov/firebase-tools
  needs:
    - prod:build
  rules:
    - if: $CI_COMMIT_BRANCH == "master"
    - when: never
  before_script:
    - echo $FIARD_PRIVATE_KEY > "$HOME/private-key.json"
    - export GOOGLE_APPLICATION_CREDENTIALS="$HOME/private-key.json"
  script:
    - firebase use "lucacesarano-com"
    - firebase deploy -m "Pipe $CI_PIPELINE_ID Build $CI_BUILD_ID" --only hosting:lucacesarano-com --non-interactive
